config/routes.rb
Blog::Application.routes.draw do
  resources :commnets
  resources :posts do
    resource :commnets
  end

  

end

app/models/commnet.rb
class Commnet < ActiveRecord::Base
  belongs_to :post
  validates :post_id,:presence => true
  validates :body,:presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :commnets
  validates :title,:presence => true
  validates :body,:presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commnets_controller.rb
class CommnetsController < ApplicationController
  before_action :set_commnet, only: [:show, :edit, :update, :destroy]

  # GET /commnets
  # GET /commnets.json
  def index
    @commnets = Commnet.all
  end

  # GET /commnets/1
  # GET /commnets/1.json
  def show
  end

  # GET /commnets/new
  def new
    @commnet = Commnet.new
  end

  # GET /commnets/1/edit
  def edit
  end

  # POST /commnets
  # POST /commnets.json
  def create
    @commnet = Commnet.new(commnet_params)

    respond_to do |format|
      if @commnet.save
        format.html { redirect_to @commnet, notice: 'Commnet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @commnet }
      else
        format.html { render action: 'new' }
        format.json { render json: @commnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commnets/1
  # PATCH/PUT /commnets/1.json
  def update
    respond_to do |format|
      if @commnet.update(commnet_params)
        format.html { redirect_to @commnet, notice: 'Commnet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @commnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commnets/1
  # DELETE /commnets/1.json
  def destroy
    @commnet.destroy
    respond_to do |format|
      format.html { redirect_to commnets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commnet
      @commnet = Commnet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commnet_params
      params.require(:commnet).permit(:title, :body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commnets_helper.rb
module CommnetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/commnets/_form.html.erb
<%= form_for(@commnet) do |f| %>
  <% if @commnet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commnet.errors.count, "error") %> prohibited this commnet from being saved:</h2>

      <ul>
      <% @commnet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commnets/edit.html.erb
<h1>Editing commnet</h1>

<%= render 'form' %>

<%= link_to 'Show', @commnet %> |
<%= link_to 'Back', commnets_path %>

app/views/commnets/index.html.erb
<h1>Listing commnets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @commnets.each do |commnet| %>
      <tr>
        <td><%= commnet.title %></td>
        <td><%= commnet.body %></td>
        <td><%= commnet.post_id %></td>
        <td><%= link_to 'Show', commnet %></td>
        <td><%= link_to 'Edit', edit_commnet_path(commnet) %></td>
        <td><%= link_to 'Destroy', commnet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commnet', new_commnet_path %>

app/views/commnets/new.html.erb
<h1>New commnet</h1>

<%= render 'form' %>

<%= link_to 'Back', commnets_path %>

app/views/commnets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @commnet.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @commnet.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @commnet.post_id %>
</p>

<%= link_to 'Edit', edit_commnet_path(@commnet) %> |
<%= link_to 'Back', commnets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>